export interface CountryStamp {
  id: string; // ISO 3166-1 alpha-3
  nameZh: string;
  nameEn: string;
  cityZh: string;
  cityEn: string;
  airportCode: string;
  region: 'asia' | 'europe' | 'americas' | 'oceania' | 'africa' | 'middle_east';
  regionZh: string;
  stampType: 'circle' | 'rectangle' | 'octagon' | 'triangle' | 'oval' | 'hexagon' | 'shield' | 'diamond';
  inkColor: string;
  accentColor: string;
}

export const COUNTRY_STAMPS: CountryStamp[] = [
  // ── 東亞 & 東南亞 ──────────────────────────────────────────
  {
    id: 'TWN',
    nameZh: '台灣',
    nameEn: 'TAIWAN',
    cityZh: '台北',
    cityEn: 'TAIPEI',
    airportCode: 'TPE / TSA',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'circle',
    inkColor: '#035096',
    accentColor: '#38bdf8',
  },
  {
    id: 'JPN',
    nameZh: '日本',
    nameEn: 'JAPAN',
    cityZh: '東京',
    cityEn: 'TOKYO',
    airportCode: 'HND / NRT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'octagon',
    inkColor: '#e63946',
    accentColor: '#fb7185',
  },
  {
    id: 'KOR',
    nameZh: '韓國',
    nameEn: 'SOUTH KOREA',
    cityZh: '首爾',
    cityEn: 'SEOUL',
    airportCode: 'ICN / GMP',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'hexagon',
    inkColor: '#1d4ed8',
    accentColor: '#60a5fa',
  },
  {
    id: 'THA',
    nameZh: '泰國',
    nameEn: 'THAILAND',
    cityZh: '曼谷',
    cityEn: 'BANGKOK',
    airportCode: 'BKK / DMK',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'diamond',
    inkColor: '#d97706',
    accentColor: '#fcd34d',
  },
  {
    id: 'VNM',
    nameZh: '越南',
    nameEn: 'VIETNAM',
    cityZh: '河內',
    cityEn: 'HANOI',
    airportCode: 'HAN / SGN',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'rounded-rect' as any,
    inkColor: '#dc2626',
    accentColor: '#f87171',
  },
  {
    id: 'SGP',
    nameZh: '新加坡',
    nameEn: 'SINGAPORE',
    cityZh: '新加坡',
    cityEn: 'SINGAPORE',
    airportCode: 'SIN CHANGI',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'octagon',
    inkColor: '#0284c7',
    accentColor: '#7dd3fc',
  },
  {
    id: 'MYS',
    nameZh: '馬來西亞',
    nameEn: 'MALAYSIA',
    cityZh: '吉隆坡',
    cityEn: 'KUALA LUMPUR',
    airportCode: 'KUL KLIA',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'oval',
    inkColor: '#2563eb',
    accentColor: '#93c5fd',
  },
  {
    id: 'IDN',
    nameZh: '印尼',
    nameEn: 'INDONESIA',
    cityZh: '峇里島',
    cityEn: 'BALI',
    airportCode: 'DPS / CGK',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'triangle',
    inkColor: '#059669',
    accentColor: '#6ee7b7',
  },
  {
    id: 'PHL',
    nameZh: '菲律賓',
    nameEn: 'PHILIPPINES',
    cityZh: '馬尼拉',
    cityEn: 'MANILA',
    airportCode: 'MNL NAIA',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'circle',
    inkColor: '#0284c7',
    accentColor: '#38bdf8',
  },
  {
    id: 'KHM',
    nameZh: '柬埔寨',
    nameEn: 'CAMBODIA',
    cityZh: '金邊',
    cityEn: 'PHNOM PENH',
    airportCode: 'PNH / REP',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'shield',
    inkColor: '#b45309',
    accentColor: '#fbbf24',
  },
  {
    id: 'LAO',
    nameZh: '寮國',
    nameEn: 'LAOS',
    cityZh: '永珍',
    cityEn: 'VIENTIANE',
    airportCode: 'VTE AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'oval',
    inkColor: '#0891b2',
    accentColor: '#67e8f9',
  },
  {
    id: 'MMR',
    nameZh: '緬甸',
    nameEn: 'MYANMAR',
    cityZh: '仰光',
    cityEn: 'YANGON',
    airportCode: 'RGN AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'rectangle',
    inkColor: '#ea580c',
    accentColor: '#fdba74',
  },
  {
    id: 'HKG',
    nameZh: '香港',
    nameEn: 'HONG KONG',
    cityZh: '香港',
    cityEn: 'HONG KONG',
    airportCode: 'HKG CHEK LAP',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'octagon',
    inkColor: '#e11d48',
    accentColor: '#fda4af',
  },
  {
    id: 'MAC',
    nameZh: '澳門',
    nameEn: 'MACAU',
    cityZh: '澳門',
    cityEn: 'MACAU',
    airportCode: 'MFM AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'circle',
    inkColor: '#059669',
    accentColor: '#a7f3d0',
  },
  {
    id: 'MNG',
    nameZh: '蒙古',
    nameEn: 'MONGOLIA',
    cityZh: '烏蘭巴托',
    cityEn: 'ULAANBAATAR',
    airportCode: 'UBN AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'shield',
    inkColor: '#2563eb',
    accentColor: '#93c5fd',
  },
  {
    id: 'CHN',
    nameZh: '中國',
    nameEn: 'CHINA',
    cityZh: '北京',
    cityEn: 'BEIJING',
    airportCode: 'PEK / PKX',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'rectangle',
    inkColor: '#dc2626',
    accentColor: '#fca5a5',
  },
  {
    id: 'BRN',
    nameZh: '汶萊',
    nameEn: 'BRUNEI',
    cityZh: '斯里巴加灣',
    cityEn: 'BANDAR SERI',
    airportCode: 'BWN AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'diamond',
    inkColor: '#ca8a04',
    accentColor: '#fef08a',
  },

  // ── 南亞 & 中亞 ──────────────────────────────────────────
  {
    id: 'IND',
    nameZh: '印度',
    nameEn: 'INDIA',
    cityZh: '新德里',
    cityEn: 'NEW DELHI',
    airportCode: 'DEL IGI',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'circle',
    inkColor: '#ea580c',
    accentColor: '#fed7aa',
  },
  {
    id: 'NPL',
    nameZh: '尼泊爾',
    nameEn: 'NEPAL',
    cityZh: '加德滿都',
    cityEn: 'KATHMANDU',
    airportCode: 'KTM TIA',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'triangle',
    inkColor: '#be123c',
    accentColor: '#fecdd3',
  },
  {
    id: 'LKA',
    nameZh: '斯里蘭卡',
    nameEn: 'SRI LANKA',
    cityZh: '可倫坡',
    cityEn: 'COLOMBO',
    airportCode: 'CMB BIA',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'oval',
    inkColor: '#b45309',
    accentColor: '#fde68a',
  },
  {
    id: 'MDV',
    nameZh: '馬爾地夫',
    nameEn: 'MALDIVES',
    cityZh: '馬列',
    cityEn: 'MALE',
    airportCode: 'MLE VIA',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'octagon',
    inkColor: '#0891b2',
    accentColor: '#67e8f9',
  },
  {
    id: 'BTN',
    nameZh: '不丹',
    nameEn: 'BHUTAN',
    cityZh: '廷布',
    cityEn: 'THIMPHU',
    airportCode: 'PBH PARO',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'shield',
    inkColor: '#d97706',
    accentColor: '#fcd34d',
  },
  {
    id: 'KAZ',
    nameZh: '哈薩克',
    nameEn: 'KAZAKHSTAN',
    cityZh: '阿拉木圖',
    cityEn: 'ALMATY',
    airportCode: 'ALA AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'hexagon',
    inkColor: '#0284c7',
    accentColor: '#7dd3fc',
  },
  {
    id: 'UZB',
    nameZh: '烏茲別克',
    nameEn: 'UZBEKISTAN',
    cityZh: '塔什干',
    cityEn: 'TASHKENT',
    airportCode: 'TAS AIRPORT',
    region: 'asia',
    regionZh: '亞洲',
    stampType: 'rectangle',
    inkColor: '#059669',
    accentColor: '#6ee7b7',
  },

  // ── 歐洲 (西歐、北歐、中歐、南歐、東歐) ──────────────────────────
  {
    id: 'GBR',
    nameZh: '英國',
    nameEn: 'UNITED KINGDOM',
    cityZh: '倫敦',
    cityEn: 'LONDON',
    airportCode: 'LHR / LGW',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'rectangle',
    inkColor: '#1e3a8a',
    accentColor: '#93c5fd',
  },
  {
    id: 'FRA',
    nameZh: '法國',
    nameEn: 'FRANCE',
    cityZh: '巴黎',
    cityEn: 'PARIS',
    airportCode: 'CDG / ORY',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'triangle',
    inkColor: '#4338ca',
    accentColor: '#a5b4fc',
  },
  {
    id: 'ITA',
    nameZh: '義大利',
    nameEn: 'ITALY',
    cityZh: '羅馬',
    cityEn: 'ROME',
    airportCode: 'FCO FIUMICINO',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'oval',
    inkColor: '#047857',
    accentColor: '#6ee7b7',
  },
  {
    id: 'DEU',
    nameZh: '德國',
    nameEn: 'GERMANY',
    cityZh: '柏林',
    cityEn: 'BERLIN',
    airportCode: 'BER AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'rectangle',
    inkColor: '#334155',
    accentColor: '#94a3b8',
  },
  {
    id: 'ESP',
    nameZh: '西班牙',
    nameEn: 'SPAIN',
    cityZh: '馬德里',
    cityEn: 'MADRID',
    airportCode: 'MAD BARAJAS',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'octagon',
    inkColor: '#dc2626',
    accentColor: '#fca5a5',
  },
  {
    id: 'PRT',
    nameZh: '葡萄牙',
    nameEn: 'PORTUGAL',
    cityZh: '里斯本',
    cityEn: 'LISBON',
    airportCode: 'LIS HUMBERTO',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'shield',
    inkColor: '#059669',
    accentColor: '#86efac',
  },
  {
    id: 'CHE',
    nameZh: '瑞士',
    nameEn: 'SWITZERLAND',
    cityZh: '蘇黎世',
    cityEn: 'ZURICH',
    airportCode: 'ZRH AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'octagon',
    inkColor: '#b91c1c',
    accentColor: '#f87171',
  },
  {
    id: 'AUT',
    nameZh: '奧地利',
    nameEn: 'AUSTRIA',
    cityZh: '維也納',
    cityEn: 'VIENNA',
    airportCode: 'VIE SCHWECHAT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'shield',
    inkColor: '#be123c',
    accentColor: '#fda4af',
  },
  {
    id: 'NLD',
    nameZh: '荷蘭',
    nameEn: 'NETHERLANDS',
    cityZh: '阿姆斯特丹',
    cityEn: 'AMSTERDAM',
    airportCode: 'AMS SCHIPHOL',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'hexagon',
    inkColor: '#ea580c',
    accentColor: '#fdba74',
  },
  {
    id: 'BEL',
    nameZh: '比利時',
    nameEn: 'BELGIUM',
    cityZh: '布魯塞爾',
    cityEn: 'BRUSSELS',
    airportCode: 'BRU BRUSSELS',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'rectangle',
    inkColor: '#ca8a04',
    accentColor: '#fde047',
  },
  {
    id: 'CZE',
    nameZh: '捷克',
    nameEn: 'CZECHIA',
    cityZh: '布拉格',
    cityEn: 'PRAGUE',
    airportCode: 'PRG VACLAV',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'oval',
    inkColor: '#1d4ed8',
    accentColor: '#93c5fd',
  },
  {
    id: 'HUN',
    nameZh: '匈牙利',
    nameEn: 'HUNGARY',
    cityZh: '布達佩斯',
    cityEn: 'BUDAPEST',
    airportCode: 'BUD LISZT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'circle',
    inkColor: '#047857',
    accentColor: '#86efac',
  },
  {
    id: 'POL',
    nameZh: '波蘭',
    nameEn: 'POLAND',
    cityZh: '華沙',
    cityEn: 'WARSAW',
    airportCode: 'WAW CHOPIN',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'shield',
    inkColor: '#e11d48',
    accentColor: '#fda4af',
  },
  {
    id: 'GRC',
    nameZh: '希臘',
    nameEn: 'GREECE',
    cityZh: '雅典',
    cityEn: 'ATHENS',
    airportCode: 'ATH ELEFTHERIOS',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'oval',
    inkColor: '#0284c7',
    accentColor: '#7dd3fc',
  },
  {
    id: 'ISL',
    nameZh: '冰島',
    nameEn: 'ICELAND',
    cityZh: '雷克雅維克',
    cityEn: 'REYKJAVIK',
    airportCode: 'KEF KEFLAVIK',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'circle',
    inkColor: '#0891b2',
    accentColor: '#a5f3fc',
  },
  {
    id: 'NOR',
    nameZh: '挪威',
    nameEn: 'NORWAY',
    cityZh: '奧斯陸',
    cityEn: 'OSLO',
    airportCode: 'OSL GARDERMOEN',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'triangle',
    inkColor: '#1d4ed8',
    accentColor: '#93c5fd',
  },
  {
    id: 'SWE',
    nameZh: '瑞典',
    nameEn: 'SWEDEN',
    cityZh: '斯德哥爾摩',
    cityEn: 'STOCKHOLM',
    airportCode: 'ARN ARLANDA',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'hexagon',
    inkColor: '#0284c7',
    accentColor: '#fde047',
  },
  {
    id: 'FIN',
    nameZh: '芬蘭',
    nameEn: 'FINLAND',
    cityZh: '赫爾辛基',
    cityEn: 'HELSINKI',
    airportCode: 'HEL VANTAA',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'octagon',
    inkColor: '#1e40af',
    accentColor: '#93c5fd',
  },
  {
    id: 'DNK',
    nameZh: '丹麥',
    nameEn: 'DENMARK',
    cityZh: '哥本哈根',
    cityEn: 'COPENHAGEN',
    airportCode: 'CPH KASTRUP',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'rectangle',
    inkColor: '#be123c',
    accentColor: '#fda4af',
  },
  {
    id: 'IRL',
    nameZh: '愛爾蘭',
    nameEn: 'IRELAND',
    cityZh: '都柏林',
    cityEn: 'DUBLIN',
    airportCode: 'DUB AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'oval',
    inkColor: '#15803d',
    accentColor: '#86efac',
  },
  {
    id: 'HRV',
    nameZh: '克羅埃西亞',
    nameEn: 'CROATIA',
    cityZh: '杜布羅夫尼克',
    cityEn: 'DUBROVNIK',
    airportCode: 'DBV / ZAG',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'shield',
    inkColor: '#dc2626',
    accentColor: '#93c5fd',
  },
  {
    id: 'SVN',
    nameZh: '斯洛維尼亞',
    nameEn: 'SLOVENIA',
    cityZh: '盧比安納',
    cityEn: 'LJUBLJANA',
    airportCode: 'LJU JOZE',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'diamond',
    inkColor: '#059669',
    accentColor: '#a7f3d0',
  },
  {
    id: 'ROU',
    nameZh: '羅馬尼亞',
    nameEn: 'ROMANIA',
    cityZh: '布加勒斯特',
    cityEn: 'BUCHAREST',
    airportCode: 'OTP OTOPENI',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'circle',
    inkColor: '#1d4ed8',
    accentColor: '#fcd34d',
  },
  {
    id: 'BGR',
    nameZh: '保加利亞',
    nameEn: 'BULGARIA',
    cityZh: '索菲亞',
    cityEn: 'SOFIA',
    airportCode: 'SOF AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'rectangle',
    inkColor: '#047857',
    accentColor: '#fca5a5',
  },
  {
    id: 'SVK',
    nameZh: '斯洛伐克',
    nameEn: 'SLOVAKIA',
    cityZh: '布拉提斯拉瓦',
    cityEn: 'BRATISLAVA',
    airportCode: 'BTS STEFANIK',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'hexagon',
    inkColor: '#2563eb',
    accentColor: '#fda4af',
  },
  {
    id: 'EST',
    nameZh: '愛沙尼亞',
    nameEn: 'ESTONIA',
    cityZh: '塔林',
    cityEn: 'TALLINN',
    airportCode: 'TLL MERI',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'octagon',
    inkColor: '#0284c7',
    accentColor: '#38bdf8',
  },
  {
    id: 'LVA',
    nameZh: '拉脫維亞',
    nameEn: 'LATVIA',
    cityZh: '里加',
    cityEn: 'RIGA',
    airportCode: 'RIX AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'shield',
    inkColor: '#991b1b',
    accentColor: '#fca5a5',
  },
  {
    id: 'LTU',
    nameZh: '立陶宛',
    nameEn: 'LITHUANIA',
    cityZh: '維爾紐斯',
    cityEn: 'VILNIUS',
    airportCode: 'VNO AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'oval',
    inkColor: '#ca8a04',
    accentColor: '#86efac',
  },
  {
    id: 'LUX',
    nameZh: '盧森堡',
    nameEn: 'LUXEMBOURG',
    cityZh: '盧森堡市',
    cityEn: 'LUXEMBOURG',
    airportCode: 'LUX FINDEL',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'diamond',
    inkColor: '#0284c7',
    accentColor: '#f87171',
  },
  {
    id: 'MLT',
    nameZh: '馬爾他',
    nameEn: 'MALTA',
    cityZh: '瓦勒他',
    cityEn: 'VALLETTA',
    airportCode: 'MLA LUQA',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'circle',
    inkColor: '#be123c',
    accentColor: '#fda4af',
  },
  {
    id: 'CYP',
    nameZh: '賽普勒斯',
    nameEn: 'CYPRUS',
    cityZh: '尼古西亞',
    cityEn: 'NICOSIA',
    airportCode: 'LCA LARNACA',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'rectangle',
    inkColor: '#d97706',
    accentColor: '#fef08a',
  },
  {
    id: 'MCO',
    nameZh: '摩納哥',
    nameEn: 'MONACO',
    cityZh: '摩納哥',
    cityEn: 'MONACO',
    airportCode: 'MCM HELIPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'shield',
    inkColor: '#dc2626',
    accentColor: '#fca5a5',
  },
  {
    id: 'SMR',
    nameZh: '聖馬利諾',
    nameEn: 'SAN MARINO',
    cityZh: '聖馬利諾',
    cityEn: 'SAN MARINO',
    airportCode: 'SAI TITANO',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'triangle',
    inkColor: '#0284c7',
    accentColor: '#bae6fd',
  },
  {
    id: 'VAT',
    nameZh: '梵蒂岡',
    nameEn: 'VATICAN CITY',
    cityZh: '梵蒂岡',
    cityEn: 'VATICAN',
    airportCode: 'VAT HOLY SEE',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'octagon',
    inkColor: '#ca8a04',
    accentColor: '#fef08a',
  },
  {
    id: 'AND',
    nameZh: '安道爾',
    nameEn: 'ANDORRA',
    cityZh: '安道爾城',
    cityEn: 'ANDORRA LA VELLA',
    airportCode: 'ALV AIRPORT',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'hexagon',
    inkColor: '#2563eb',
    accentColor: '#fca5a5',
  },
  {
    id: 'LIE',
    nameZh: '列支敦斯登',
    nameEn: 'LIECHTENSTEIN',
    cityZh: '瓦都茲',
    cityEn: 'VADUZ',
    airportCode: 'VDZ VADUZ',
    region: 'europe',
    regionZh: '歐洲',
    stampType: 'diamond',
    inkColor: '#1e40af',
    accentColor: '#fca5a5',
  },

  // ── 美洲 (北美洲、中美洲、南美洲) ──────────────────────────
  {
    id: 'USA',
    nameZh: '美國',
    nameEn: 'UNITED STATES',
    cityZh: '紐約',
    cityEn: 'NEW YORK',
    airportCode: 'JFK / LAX',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'rectangle',
    inkColor: '#1d4ed8',
    accentColor: '#ef4444',
  },
  {
    id: 'CAN',
    nameZh: '加拿大',
    nameEn: 'CANADA',
    cityZh: '溫哥華',
    cityEn: 'VANCOUVER',
    airportCode: 'YVR / YYZ',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'shield',
    inkColor: '#dc2626',
    accentColor: '#fca5a5',
  },
  {
    id: 'MEX',
    nameZh: '墨西哥',
    nameEn: 'MEXICO',
    cityZh: '墨西哥城',
    cityEn: 'MEXICO CITY',
    airportCode: 'MEX BENITO JUAREZ',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'circle',
    inkColor: '#059669',
    accentColor: '#ef4444',
  },
  {
    id: 'BRA',
    nameZh: '巴西',
    nameEn: 'BRAZIL',
    cityZh: '里約熱內盧',
    cityEn: 'RIO DE JANEIRO',
    airportCode: 'GIG / GRU',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'diamond',
    inkColor: '#16a34a',
    accentColor: '#facc15',
  },
  {
    id: 'ARG',
    nameZh: '阿根廷',
    nameEn: 'ARGENTINA',
    cityZh: '布宜諾斯艾利斯',
    cityEn: 'BUENOS AIRES',
    airportCode: 'EZE EZEIZA',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'oval',
    inkColor: '#0284c7',
    accentColor: '#fde047',
  },
  {
    id: 'CHL',
    nameZh: '智利',
    nameEn: 'CHILE',
    cityZh: '聖地牙哥',
    cityEn: 'SANTIAGO',
    airportCode: 'SCL BENITEZ',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'triangle',
    inkColor: '#dc2626',
    accentColor: '#93c5fd',
  },
  {
    id: 'PER',
    nameZh: '秘魯',
    nameEn: 'PERU',
    cityZh: '庫斯科',
    cityEn: 'CUSCO',
    airportCode: 'CUZ / LIM',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'octagon',
    inkColor: '#b91c1c',
    accentColor: '#fcd34d',
  },
  {
    id: 'COL',
    nameZh: '哥倫比亞',
    nameEn: 'COLOMBIA',
    cityZh: '波哥大',
    cityEn: 'BOGOTA',
    airportCode: 'BOG EL DORADO',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'hexagon',
    inkColor: '#ca8a04',
    accentColor: '#60a5fa',
  },
  {
    id: 'CRI',
    nameZh: '哥斯大黎加',
    nameEn: 'COSTA RICA',
    cityZh: '聖荷西',
    cityEn: 'SAN JOSE',
    airportCode: 'SJO SANTAMARIA',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'circle',
    inkColor: '#0284c7',
    accentColor: '#ef4444',
  },
  {
    id: 'PAN',
    nameZh: '巴拿馬',
    nameEn: 'PANAMA',
    cityZh: '巴拿馬城',
    cityEn: 'PANAMA CITY',
    airportCode: 'PTY TOCUMEN',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'rectangle',
    inkColor: '#1e40af',
    accentColor: '#f87171',
  },
  {
    id: 'CUB',
    nameZh: '古巴',
    nameEn: 'CUBA',
    cityZh: '哈瓦那',
    cityEn: 'HAVANA',
    airportCode: 'HAV MARTI',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'shield',
    inkColor: '#0284c7',
    accentColor: '#ef4444',
  },
  {
    id: 'ECU',
    nameZh: '厄瓜多',
    nameEn: 'ECUADOR',
    cityZh: '基多',
    cityEn: 'QUITO',
    airportCode: 'UIO SUCRE',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'oval',
    inkColor: '#ca8a04',
    accentColor: '#38bdf8',
  },
  {
    id: 'BOL',
    nameZh: '玻利維亞',
    nameEn: 'BOLIVIA',
    cityZh: '拉巴斯',
    cityEn: 'LA PAZ',
    airportCode: 'LPB EL ALTO',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'triangle',
    inkColor: '#15803d',
    accentColor: '#facc15',
  },
  {
    id: 'URY',
    nameZh: '烏拉圭',
    nameEn: 'URUGUAY',
    cityZh: '蒙特維多',
    cityEn: 'MONTEVIDEO',
    airportCode: 'MVD CARRASCO',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'octagon',
    inkColor: '#0284c7',
    accentColor: '#fef08a',
  },
  {
    id: 'PRY',
    nameZh: '巴拉圭',
    nameEn: 'PARAGUAY',
    cityZh: '亞松森',
    cityEn: 'ASUNCION',
    airportCode: 'ASU PETTIROSSI',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'diamond',
    inkColor: '#dc2626',
    accentColor: '#93c5fd',
  },
  {
    id: 'GTM',
    nameZh: '瓜地馬拉',
    nameEn: 'GUATEMALA',
    cityZh: '瓜地馬拉市',
    cityEn: 'GUATEMALA CITY',
    airportCode: 'GUA AURORA',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'circle',
    inkColor: '#0284c7',
    accentColor: '#bae6fd',
  },
  {
    id: 'JAM',
    nameZh: '牙買加',
    nameEn: 'JAMAICA',
    cityZh: '京斯敦',
    cityEn: 'KINGSTON',
    airportCode: 'KIN NORMAN MANLEY',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'hexagon',
    inkColor: '#16a34a',
    accentColor: '#facc15',
  },
  {
    id: 'BHS',
    nameZh: '巴哈馬',
    nameEn: 'BAHAMAS',
    cityZh: '拿索',
    cityEn: 'NASSAU',
    airportCode: 'NAS PINDLING',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'shield',
    inkColor: '#0891b2',
    accentColor: '#fef08a',
  },
  {
    id: 'DOM',
    nameZh: '多明尼加',
    nameEn: 'DOMINICAN REP',
    cityZh: '聖多明哥',
    cityEn: 'SANTO DOMINGO',
    airportCode: 'SDQ AMERICAS',
    region: 'americas',
    regionZh: '美洲',
    stampType: 'rectangle',
    inkColor: '#1d4ed8',
    accentColor: '#fca5a5',
  },

  // ── 大洋洲 ──────────────────────────────────────────
  {
    id: 'AUS',
    nameZh: '澳洲',
    nameEn: 'AUSTRALIA',
    cityZh: '雪梨',
    cityEn: 'SYDNEY',
    airportCode: 'SYD KINGSFORD',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'diamond',
    inkColor: '#047857',
    accentColor: '#facc15',
  },
  {
    id: 'NZL',
    nameZh: '紐西蘭',
    nameEn: 'NEW ZEALAND',
    cityZh: '奧克蘭',
    cityEn: 'AUCKLAND',
    airportCode: 'AKL AIRPORT',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'oval',
    inkColor: '#1e3a8a',
    accentColor: '#f87171',
  },
  {
    id: 'FJI',
    nameZh: '斐濟',
    nameEn: 'FIJI',
    cityZh: '蘇瓦',
    cityEn: 'SUVA',
    airportCode: 'NAN NADI',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'circle',
    inkColor: '#0284c7',
    accentColor: '#7dd3fc',
  },
  {
    id: 'PLW',
    nameZh: '帛琉',
    nameEn: 'PALAU',
    cityZh: '柯羅',
    cityEn: 'KOROR',
    airportCode: 'ROR AIRPORT',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'octagon',
    inkColor: '#0ea5e9',
    accentColor: '#fef08a',
  },
  {
    id: 'GUM',
    nameZh: '關島',
    nameEn: 'GUAM',
    cityZh: '阿加尼亞',
    cityEn: 'HAGATNA',
    airportCode: 'GUM WON PAT',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'triangle',
    inkColor: '#0369a1',
    accentColor: '#f87171',
  },
  {
    id: 'PYF',
    nameZh: '大溪地',
    nameEn: 'TAHITI',
    cityZh: '帕比提',
    cityEn: 'PAPEETE',
    airportCode: 'PPT FAA A',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'shield',
    inkColor: '#e11d48',
    accentColor: '#fda4af',
  },
  {
    id: 'WSM',
    nameZh: '薩摩亞',
    nameEn: 'SAMOA',
    cityZh: '阿庇亞',
    cityEn: 'APIA',
    airportCode: 'APW FALEOLE',
    region: 'oceania',
    regionZh: '大洋洲',
    stampType: 'hexagon',
    inkColor: '#b91c1c',
    accentColor: '#93c5fd',
  },

  // ── 中東 & 西亞 ──────────────────────────────────────────
  {
    id: 'ARE',
    nameZh: '阿拉伯聯合大公國',
    nameEn: 'UAE',
    cityZh: '杜拜',
    cityEn: 'DUBAI',
    airportCode: 'DXB / DWC',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'octagon',
    inkColor: '#b45309',
    accentColor: '#86efac',
  },
  {
    id: 'TUR',
    nameZh: '土耳其',
    nameEn: 'TURKEY',
    cityZh: '伊斯坦堡',
    cityEn: 'ISTANBUL',
    airportCode: 'IST / SAW',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'circle',
    inkColor: '#dc2626',
    accentColor: '#fca5a5',
  },
  {
    id: 'QAT',
    nameZh: '卡達',
    nameEn: 'QATAR',
    cityZh: '杜哈',
    cityEn: 'DOHA',
    airportCode: 'DOH HAMAD',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'shield',
    inkColor: '#881337',
    accentColor: '#fecdd3',
  },
  {
    id: 'SAU',
    nameZh: '沙烏地阿拉伯',
    nameEn: 'SAUDI ARABIA',
    cityZh: '利雅德',
    cityEn: 'RIYADH',
    airportCode: 'RUH KHALID',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'rectangle',
    inkColor: '#15803d',
    accentColor: '#86efac',
  },
  {
    id: 'JOR',
    nameZh: '約旦',
    nameEn: 'JORDAN',
    cityZh: '安曼',
    cityEn: 'AMMAN',
    airportCode: 'AMM ALIA',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'triangle',
    inkColor: '#b91c1c',
    accentColor: '#86efac',
  },
  {
    id: 'ISR',
    nameZh: '以色列',
    nameEn: 'ISRAEL',
    cityZh: '特拉維夫',
    cityEn: 'TEL AVIV',
    airportCode: 'TLV BEN GURION',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'hexagon',
    inkColor: '#1d4ed8',
    accentColor: '#93c5fd',
  },
  {
    id: 'OMN',
    nameZh: '阿曼',
    nameEn: 'OMAN',
    cityZh: '馬斯喀特',
    cityEn: 'MUSCAT',
    airportCode: 'MCT SEEB',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'oval',
    inkColor: '#be123c',
    accentColor: '#86efac',
  },
  {
    id: 'KWT',
    nameZh: '科威特',
    nameEn: 'KUWAIT',
    cityZh: '科威特城',
    cityEn: 'KUWAIT CITY',
    airportCode: 'KWI AIRPORT',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'diamond',
    inkColor: '#047857',
    accentColor: '#f87171',
  },
  {
    id: 'BHR',
    nameZh: '巴林',
    nameEn: 'BAHRAIN',
    cityZh: '麥納瑪',
    cityEn: 'MANAMA',
    airportCode: 'BAH MUHARRAQ',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'circle',
    inkColor: '#dc2626',
    accentColor: '#fca5a5',
  },
  {
    id: 'GEO',
    nameZh: '喬治亞',
    nameEn: 'GEORGIA',
    cityZh: '提比里斯',
    cityEn: 'TBILISI',
    airportCode: 'TBS AIRPORT',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'shield',
    inkColor: '#991b1b',
    accentColor: '#f87171',
  },
  {
    id: 'AZE',
    nameZh: '亞塞拜然',
    nameEn: 'AZERBAIJAN',
    cityZh: '巴庫',
    cityEn: 'BAKU',
    airportCode: 'GYD ALIYEV',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'octagon',
    inkColor: '#0284c7',
    accentColor: '#86efac',
  },
  {
    id: 'ARM',
    nameZh: '亞美尼亞',
    nameEn: 'ARMENIA',
    cityZh: '葉里溫',
    cityEn: 'YEREVAN',
    airportCode: 'EVN ZVARTNOTS',
    region: 'middle_east',
    regionZh: '中東',
    stampType: 'rectangle',
    inkColor: '#b45309',
    accentColor: '#93c5fd',
  },

  // ── 非洲 ──────────────────────────────────────────
  {
    id: 'EGY',
    nameZh: '埃及',
    nameEn: 'EGYPT',
    cityZh: '開羅',
    cityEn: 'CAIRO',
    airportCode: 'CAI AIRPORT',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'triangle',
    inkColor: '#b45309',
    accentColor: '#fde047',
  },
  {
    id: 'MAR',
    nameZh: '摩洛哥',
    nameEn: 'MOROCCO',
    cityZh: '馬拉喀什',
    cityEn: 'MARRAKECH',
    airportCode: 'RAK MENARA',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'octagon',
    inkColor: '#b91c1c',
    accentColor: '#86efac',
  },
  {
    id: 'ZAF',
    nameZh: '南非',
    nameEn: 'SOUTH AFRICA',
    cityZh: '開普敦',
    cityEn: 'CAPE TOWN',
    airportCode: 'CPT / JNB',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'shield',
    inkColor: '#15803d',
    accentColor: '#facc15',
  },
  {
    id: 'KEN',
    nameZh: '肯亞',
    nameEn: 'KENYA',
    cityZh: '奈洛比',
    cityEn: 'NAIROBI',
    airportCode: 'NBO KENYATTA',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'circle',
    inkColor: '#991b1b',
    accentColor: '#86efac',
  },
  {
    id: 'TZA',
    nameZh: '坦尚尼亞',
    nameEn: 'TANZANIA',
    cityZh: '吉力馬札羅',
    cityEn: 'KILIMANJARO',
    airportCode: 'JRO AIRPORT',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'diamond',
    inkColor: '#0284c7',
    accentColor: '#facc15',
  },
  {
    id: 'MUS',
    nameZh: '模里西斯',
    nameEn: 'MAURITIUS',
    cityZh: '路易港',
    cityEn: 'PORT LOUIS',
    airportCode: 'MRU RAMGOOLAM',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'oval',
    inkColor: '#be123c',
    accentColor: '#fcd34d',
  },
  {
    id: 'SYC',
    nameZh: '塞席爾',
    nameEn: 'SEYCHELLES',
    cityZh: '維多利亞',
    cityEn: 'VICTORIA',
    airportCode: 'SEZ POINTE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'hexagon',
    inkColor: '#0284c7',
    accentColor: '#f87171',
  },
  {
    id: 'MDG',
    nameZh: '馬達加斯加',
    nameEn: 'MADAGASCAR',
    cityZh: '安塔那那利佛',
    cityEn: 'ANTANANARIVO',
    airportCode: 'TNR IVATO',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'rectangle',
    inkColor: '#15803d',
    accentColor: '#fca5a5',
  },
  {
    id: 'TUN',
    nameZh: '突尼西亞',
    nameEn: 'TUNISIA',
    cityZh: '突尼斯',
    cityEn: 'TUNIS',
    airportCode: 'TUN CARTHAGE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'circle',
    inkColor: '#dc2626',
    accentColor: '#fda4af',
  },
  {
    id: 'ETH',
    nameZh: '衣索比亞',
    nameEn: 'ETHIOPIA',
    cityZh: '阿迪斯阿貝巴',
    cityEn: 'ADDIS ABABA',
    airportCode: 'ADD BOLE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'shield',
    inkColor: '#15803d',
    accentColor: '#fde047',
  },
  {
    id: 'NAM',
    nameZh: '納米比亞',
    nameEn: 'NAMIBIA',
    cityZh: '溫荷克',
    cityEn: 'WINDHOEK',
    airportCode: 'WDH KUTAKO',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'octagon',
    inkColor: '#0284c7',
    accentColor: '#fdba74',
  },
  {
    id: 'BWA',
    nameZh: '波札那',
    nameEn: 'BOTSWANA',
    cityZh: '嘉柏隆里',
    cityEn: 'GABORONE',
    airportCode: 'GBE SERETSE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'diamond',
    inkColor: '#0ea5e9',
    accentColor: '#38bdf8',
  },
  {
    id: 'RWA',
    nameZh: '盧安達',
    nameEn: 'RWANDA',
    cityZh: '吉佳利',
    cityEn: 'KIGALI',
    airportCode: 'KGL KANOMBE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'oval',
    inkColor: '#0284c7',
    accentColor: '#86efac',
  },
  {
    id: 'GHA',
    nameZh: '迦納',
    nameEn: 'GHANA',
    cityZh: '阿克拉',
    cityEn: 'ACCRA',
    airportCode: 'ACC KOTOKA',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'triangle',
    inkColor: '#dc2626',
    accentColor: '#fde047',
  },
  {
    id: 'NGA',
    nameZh: '奈及利亞',
    nameEn: 'NIGERIA',
    cityZh: '拉哥斯',
    cityEn: 'LAGOS',
    airportCode: 'LOS MUHAMMED',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'rectangle',
    inkColor: '#15803d',
    accentColor: '#86efac',
  },
  {
    id: 'SEN',
    nameZh: '塞內加爾',
    nameEn: 'SENEGAL',
    cityZh: '達卡',
    cityEn: 'DAKAR',
    airportCode: 'DSS DIASS',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'hexagon',
    inkColor: '#16a34a',
    accentColor: '#fde047',
  },
  {
    id: 'ZWE',
    nameZh: '辛巴威',
    nameEn: 'ZIMBABWE',
    cityZh: '哈拉雷',
    cityEn: 'HARARE',
    airportCode: 'HRE MUGABE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'circle',
    inkColor: '#15803d',
    accentColor: '#f87171',
  },
  {
    id: 'ZMB',
    nameZh: '尚比亞',
    nameEn: 'ZAMBIA',
    cityZh: '路沙卡',
    cityEn: 'LUSAKA',
    airportCode: 'LUN KAUNDA',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'shield',
    inkColor: '#ea580c',
    accentColor: '#86efac',
  },
  {
    id: 'UGA',
    nameZh: '烏干達',
    nameEn: 'UGANDA',
    cityZh: '坎帕拉',
    cityEn: 'KAMPALA',
    airportCode: 'EBB ENTEBBE',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'octagon',
    inkColor: '#ca8a04',
    accentColor: '#f87171',
  },
  {
    id: 'MOZ',
    nameZh: '莫三比克',
    nameEn: 'MOZAMBIQUE',
    cityZh: '馬普托',
    cityEn: 'MAPUTO',
    airportCode: 'MPM MACHEL',
    region: 'africa',
    regionZh: '非洲',
    stampType: 'diamond',
    inkColor: '#059669',
    accentColor: '#fde047',
  }
];
